apiVersion: v1
kind: Secret
metadata:
  name: {{ include "subscription.fullname" . }}
  labels:
{{ include "subscription.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ .Values.redis.host | b64enc }}
  REDIS_PORT: {{ .Values.redis.port | default 6379 | toString | b64enc }}
  RABBIT_USERNAME: {{ .Values.rabbitmq.username | b64enc }}
  RABBIT_HOST: {{ .Values.rabbitmq.host | b64enc }}
  RABBIT_PROTOCOL: {{ .Values.rabbitmq.protocol | default "amqps" | b64enc }}
  RABBIT_PORT: {{ .Values.rabbitmq.port | default 5672 | toString | b64enc }}
  {{- if and .Values.rabbitmq.password (not .Values.rabbitmq.existingSecret) }}
  RABBIT_PASSWORD: {{ .Values.rabbitmq.password | b64enc }}
  {{- end }}