name: Release Helm Packages

on:
  push:
    tags:
      - 'v*'
jobs:
  wait:
    runs-on: ubuntu-latest
    name: Wait for tests
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: "${{ github.sha }}"
          running-workflow-name: 'test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-regexp: run-tests.*
  release:
    needs: [ wait ]
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        package: [
          manager,
          router,
          subscription
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'src'
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Charts
        shell: bash
        run: |
          find src/${FOLDER}/ -type f -name 'Chart.yaml' | sed -r 's|/[^/]+$||' | sort | uniq | xargs -L 1 helm dep up
          echo "src/${FOLDER}/"
          helm package "src/${FOLDER}/" -u -d dest --version ${VERSION}
        env:
          FOLDER: ${{ matrix.package }}
          VERSION: "${{ github.ref_name }}"
          
      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.4.1
        with:
          name: ${{ matrix.package }}
          repository: ${{ github.repository }}
          path: "src/${{ matrix.package }}"
          tag: "${{ github.ref_name }}"
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

