name: Build and test Helm packages
on:
  push:
    branches:
      - "**"
  pull_request_target:
    types:
      - ready_for_review
    branches:
      - main
  workflow_dispatch: null

jobs:
  test:
    runs-on: ubuntu-latest
    name: run-tests
    strategy:
      fail-fast: false
      matrix:
        package: [
          iris-manager,
          iris-router,
          iris-subscription
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Helm Lint ${{ matrix.package }}
        run: helm lint ${{ matrix.package }}
      - name: Helm Package ${{ matrix.package }}
        run: helm package ${{ matrix.package }}
